version: "3.7"
services:

  db:
    image: "mysql:5.7"
    volumes:  
    - db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    deploy:
        replicas: 4
    depends_on:
    - db
    image: wordpress:latest
    volumes:
    - wp_vol:/var/www/html
    ports: 
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data:
  wp_vol: